# -- Root Directories --
pyseer_out: "output/gwas/pyseer"
gwas_tree: "output/gwas/tree"
gwas_data: "output/gwas"
gwas_snippy: "output/gwas/snippy"
gwas_unitig: "output/gwas/unitig"
gwas_pyseer: "output/gwas/pyseer_results"

# -- Scripts --
r_effect_bubble : "scripts/plot_effect_bubble.R"
gwas_summarize : "scripts/summarize_gwas_results.py"
gwas_filter_hits : "scripts/filter_significant_hits.py"
gwas_phandango : "scripts/phandango_plot.py"
pyseer_phylogeny : "scripts/pyseer_scripts/phylogeny_distance.py"
pyseer_qqplot: "scripts/pyseer_scripts/qq_plot.py"
pyseer_patterns: "scripts/pyseer_scripts/count_patterns.py"

# -- Conda enviroments --
conda_fasttree: "envs/fasttree.yml"
conda_unitig: "envs/unitig_caller.yml"
conda_pyseer: "envs/pyseer.yml"
conda_snippy: "envs/snippy.yml"
conda_roary: "envs/roary.yml"
conda_r: "envs/r_env.yml"

#TODO ADD THIS
# -- Input Parameters --
prokka_out: "../snakemake_pipeline/output/prokka" ## CHANGE
ref_fasta: "reference_genome/Ng_ATCC19424.fasta"
ref_gff: "reference_genome/reference_annotation/ATCC19424.gff"
phen_table: "genomes_tables/phen_table.tsv"
max_threads: 64